const PRODUCT_SELECTED = 'PRODUCT_SELECTED'
const PRODUCT_DESELECTED = 'PRODUCT_DESELECTED'
const PRODUCT_PRESET = 'PRODUCT_PRESET'
const PRODUCT_REMOVE_ALL = 'PRODUCT_REMOVE_ALL'

export default {
  PRODUCT_SELECTED,
  PRODUCT_DESELECTED,
  PRODUCT_PRESET,
  PRODUCT_REMOVE_ALL
}
